<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * ContactRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function contactCount(Request $request, Controller $controller)
    {
        $controller->get('appbundle.utils')->setCustomerConnection($request, $controller);

        return $this->getEntityManager('customer')->createQuery("SELECT COUNT(contact.contact_id) FROM AppBundle:Contact contact WHERE contact.is_deleted = false")->getResult(Query::HYDRATE_SINGLE_SCALAR);
    }

    public function getContactNames(Request $request, Controller $controller)
    {
        $controller->get('appbundle.utils')->setCustomerConnection($request, $controller);
        $man = $this->getEntityManager('contact');
        return $man->createQueryBuilder()
            ->select('c.contact_id, c.contact_name')
            ->from('AppBundle:Contact', 'c')
            ->where('c.is_deleted = false')
            ->orderBy('c.contact_name', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
