<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * DocumentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function documentCount(Request $request, Controller $controller)
    {
        $controller->get('appbundle.utils')->setCustomerConnection($request, $controller);

        return $this->getEntityManager('customer')->createQuery("SELECT COUNT(document.document_id) FROM AppBundle:Document document WHERE document.is_deleted = false AND document.is_temp = FALSE")->getResult(Query::HYDRATE_SINGLE_SCALAR);
    }
}
