<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * DocumentFileRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DocumentFileRepository extends EntityRepository
{
    public function fileCount(Request $request, Controller $controller)
    {
        $controller->get('appbundle.utils')->setCustomerConnection($request, $controller);

        return $this->getEntityManager('customer')->createQuery("SELECT COUNT(file.file_id) FROM AppBundle:DocumentFile file")->getResult(Query::HYDRATE_SINGLE_SCALAR);
    }

    public function diskUsage(Request $request, Controller $controller)
    {
        $controller->get('appbundle.utils')->setCustomerConnection($request, $controller);

        return $this->getEntityManager('customer')->createQuery("SELECT COUNT(file.size) FROM AppBundle:DocumentFile file")->getResult(Query::HYDRATE_SINGLE_SCALAR);
    }
}
